"""add relationship to meal_plans and recipes

Revision ID: 609d46d0f259
Revises: 73facbecd0c7
Create Date: 2026-03-14 21:58:26.295193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '609d46d0f259'
down_revision: Union[str, Sequence[str], None] = '73facbecd0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_items', sa.Column('meal_slot', sa.String(), nullable=False))
    op.drop_column('meal_plan_items', 'meal_type')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('meal_plan_items', sa.Column('meal_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('meal_plan_items', 'meal_slot')
    # ### end Alembic commands ###
