"""add funfact to recipe model

Revision ID: 907f8a95f03b
Revises: b94cf7a30af0
Create Date: 2026-03-15 04:28:29.296088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907f8a95f03b'
down_revision: Union[str, Sequence[str], None] = 'b94cf7a30af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('funfacts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'funfacts')
    # ### end Alembic commands ###
