"""Add cuisine vibe in request

Revision ID: b67d123e4697
Revises: f0acacbc5a61
Create Date: 2026-03-15 02:56:14.090044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67d123e4697'
down_revision: Union[str, Sequence[str], None] = 'f0acacbc5a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_requests', sa.Column('cuisine_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan_requests', 'cuisine_type')
    # ### end Alembic commands ###
