"""Update meal plan request field

Revision ID: b94cf7a30af0
Revises: b67d123e4697
Create Date: 2026-03-15 03:23:21.965786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94cf7a30af0'
down_revision: Union[str, Sequence[str], None] = 'b67d123e4697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal_plan_requests', 'budget_per_meal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('meal_plan_requests', 'time_per_meal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meal_plan_requests', 'dietary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('meal_plan_requests', 'mode',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal_plan_requests', 'mode',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meal_plan_requests', 'dietary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meal_plan_requests', 'time_per_meal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meal_plan_requests', 'budget_per_meal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
