import { getStoredUserId, setStoredUserId } from './storage'

const BASE = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000'

const FRONTEND_TO_API_MODE = {
  glow: 'Glow-up',
  plant: 'Green Queen',
  fancy: 'Fancy Era',
  beast: 'Beast Mode',
  quick: 'Snack Attack',
  exam: 'Exam Mode',
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value))
}

function toNumber(value, fallback = 0) {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

function normalizeList(value) {
  if (Array.isArray(value)) return value.filter(Boolean)
  if (typeof value === 'string' && value.trim()) return [value.trim()]
  return []
}

function deriveTags(recipe, context) {
  const tags = []
  const protein = toNumber(recipe.protein)
  const carbs = toNumber(recipe.carbs)
  const calories = toNumber(recipe.calories)
  const dietary = String(context.dietary || '').toLowerCase()
  const time = toNumber(context.timePerMeal, 20)

  if (protein >= 25) tags.push('protein')
  if (carbs >= 40) tags.push('carb')
  if (calories <= 450) tags.push('balanced')
  if (time <= 15) tags.push('quick')
  if (dietary.includes('vegetarian') || dietary.includes('vegan')) tags.push('veggie')

  return tags.length ? tags : ['balanced']
}

function computeFuel(recipe) {
  const protein = toNumber(recipe.protein)
  const carbs = toNumber(recipe.carbs)
  const fat = toNumber(recipe.fat)
  const calories = toNumber(recipe.calories)
  const raw = 55 + protein * 0.8 + carbs * 0.15 - fat * 0.2 + (calories >= 300 && calories <= 700 ? 8 : 0)
  return clamp(Math.round(raw), 65, 96)
}

function toFrontendRecipe(recipe, index, context) {
  const ingredients = normalizeList(recipe.ingredients)
  const steps = normalizeList(recipe.steps)
  const fuel = computeFuel(recipe)
  const tags = deriveTags(recipe, context)
  const cuisine = context.cuisineType && context.cuisineType !== 'Anything' ? context.cuisineType : 'Mama special'
  const time = toNumber(context.timePerMeal, 20)
  const cost = toNumber(context.budgetPerMeal, 8)

  return {
    id: recipe.id,
    name: recipe.title || `Recipe ${index + 1}`,
    flag: '🍽️',
    cuisine,
    mode: context.weekMode,
    time,
    cost,
    fuel,
    cal: toNumber(recipe.calories, 400),
    pro: `${toNumber(recipe.protein, 20)}g`,
    carb: `${toNumber(recipe.carbs, 45)}g`,
    fat: `${toNumber(recipe.fat, 12)}g`,
    sugar: '0g',
    tags,
    funFact: recipe.funfacts || 'Freshly generated by mama for your week.',
    steps: steps.length ? steps : ['Prep ingredients', 'Cook everything', 'Serve warm'],
    miss: ingredients,
    ingredients,
  }
}

function buildErrorMessage(status, payload) {
  if (payload?.detail && typeof payload.detail === 'string') {
    return payload.detail
  }
  return `API error: ${status}`
}

async function apiFetch(path, options = {}) {
  const userId = getStoredUserId()
  const headers = {
    'Content-Type': 'application/json',
    ...(options.headers || {}),
  }

  if (userId) {
    headers['X-User-ID'] = userId
  }

  let res

  try {
    res = await fetch(`${BASE}${path}`, {
      ...options,
      headers,
    })
  } catch (error) {
    throw new Error(
      'Could not connect to the backend. Make sure FastAPI is running on http://127.0.0.1:8000.'
    )
  }

  if (!res.ok) {
    let payload = null
    try {
      payload = await res.json()
    } catch {}
    throw new Error(buildErrorMessage(res.status, payload))
  }

  if (res.status === 204) return null
  return res.json()
}

export function getUserId() {
  return getStoredUserId()
}

export async function createUser(username) {
  const user = await apiFetch('/users/', {
    method: 'POST',
    body: JSON.stringify({ username }),
  })

  if (user?.id) {
    setStoredUserId(user.id)
  }

  return user
}

export async function getHome() {
  return apiFetch('/home/')
}

export async function getRecipeById(recipeId) {
  return apiFetch(`/recipes/${recipeId}`)
}

export async function createMealPlanRequest(weekMode) {
  const mode = FRONTEND_TO_API_MODE[weekMode] || FRONTEND_TO_API_MODE.glow

  return apiFetch('/meal-plan-requests/', {
    method: 'POST',
    body: JSON.stringify({ mode }),
  })
}

export async function updateMealPlanRequest(requestId, payload) {
  return apiFetch(`/meal-plan-requests/${requestId}`, {
    method: 'PATCH',
    body: JSON.stringify(payload),
  })
}

export async function generateRecipes(requestId, context) {
  const data = await apiFetch(`/recipes/generate/${requestId}`, {
    method: 'POST',
  })

  return {
    ...data,
    recipes: (data.recipes || []).map((recipe, index) => toFrontendRecipe(recipe, index, context)),
  }
}

export async function regenerateRecipes(requestId, context) {
  const data = await apiFetch(`/recipes/regenerate/${requestId}`, {
    method: 'POST',
  })

  return {
    ...data,
    recipes: (data.recipes || []).map((recipe, index) =>
      toFrontendRecipe(recipe, index, context)
    ),
  }
}

export async function generateRecipeDeck({
  weekMode,
  budgetPerMeal,
  timePerMeal,
  cuisineType,
  dietary,
}) {
  const request = await createMealPlanRequest(weekMode)

  await updateMealPlanRequest(request.request_id, {
    budget_per_meal: budgetPerMeal,
    time_per_meal: timePerMeal,
    cuisine_type: cuisineType,
    dietary,
  })

  const recipes = await generateRecipes(request.request_id, {
    weekMode,
    budgetPerMeal,
    timePerMeal,
    cuisineType,
    dietary,
  })

  return {
    requestId: request.request_id,
    recipes: recipes.recipes,
  }
}

export async function saveMealPlan({ startDate, items }) {
  return apiFetch('/meal-plans/', {
    method: 'POST',
    body: JSON.stringify({
      start_date: startDate,
      items,
    }),
  })
}

export async function generateShoppingList(mealPlanId) {
  return apiFetch(`/shopping-list/${mealPlanId}`, {
    method: 'POST',
  })
}

export async function getShoppingList(mealPlanId) {
  return apiFetch(`/shopping-list/${mealPlanId}`)
}

export async function toggleShoppingListItem(itemId) {
  return apiFetch(`/shopping-list/item/${itemId}`, {
    method: 'PATCH',
  })
}
