// ─── WEEK MODES ───────────────────────────────────────────────

export const WEEK_MODES = [
  { key:'glow',  name:'Glow-Up',      emoji:'✨', color:'#F5C842', desc:'balanced, feel-good vibes'        },
  { key:'beast', name:'Beast Mode',   emoji:'💪', color:'#FF6B5B', desc:'high protein, gym fuel'          },
  { key:'plant', name:'Plant Power',  emoji:'🌱', color:'#7ED8A4', desc:'plant-based, clean & energizing' },
  { key:'quick', name:'Quick Fuel',   emoji:'⚡', color:'#C8F135', desc:'fast meals, ready in 10 mins'    },
  { key:'fancy', name:'Rich Kid',    emoji:'👑', color:'#B8A0F8', desc:'elevated, impress yourself'      },
  { key:'exam',  name:'Academic Weapon',    emoji:'📚', color:'#AAAAAA', desc:'focus, brain fuel'               },
];


// ─── RECIPES ──────────────────────────────────────────────────
export const RECIPES = [
  {
    id:1, flag:'🍚', name:'Garlic Fried Rice', cuisine:'Chinese-Aussie',
    mode:'snack', time:10, cost:3, fuel:82,
    cal:420, pro:'14g', carb:'65g', fat:'10g', sugar:'2g',
    tags:['carb','quick'],
    funFact:'Fried rice was invented in China around 600 AD as a way to use up leftover rice. The original zero-waste meal — 1,400 years before sustainability was trending 🌱',
    steps:['Heat 2 tbsp oil in wok on HIGH','Fry 3 cloves minced garlic 30s until golden','Add cold cooked rice, break up clumps, stir-fry 4 mins','Push rice aside, crack 2 eggs in the gap','Scramble eggs as they set, fold through rice','Season with soy sauce + sesame oil + white pepper'],
    miss:['garlic ($1)'],
    tips:['Use day-old cold rice — fresh rice gets mushy','HIGH heat is the secret. Don\'t be shy with the flame','A splash of fish sauce instead of soy = next level'],
  },
  {
    id:2, flag:'🍜', name:'Vietnamese Pho', cuisine:'Vietnamese',
    mode:'glow', time:25, cost:7, fuel:88,
    cal:380, pro:'28g', carb:'42g', fat:'8g', sugar:'3g',
    tags:['protein','hearty'],
    funFact:'The name "Pho" likely comes from the French "pot-au-feu" — a beef stew brought to Vietnam during colonisation. Vietnam took the concept and made it infinitely better 🇻🇳',
    steps:['Simmer chicken in 600ml water with ginger + star anise 20 mins','Remove chicken, shred with two forks','Cook rice noodles per packet, drain and rinse cold','Add fish sauce + pinch of sugar to broth, taste and adjust','Bowl: noodles + chicken + hot broth poured over','Top with bean sprouts + herbs + lime + hoisin'],
    miss:['rice noodles ($2)','star anise ($1.50)'],
    tips:['The broth is everything — don\'t skip the ginger','Add lime juice right before eating, not before','Bean sprouts should stay crunchy — add last minute'],
  },
  {
    id:3, flag:'🍳', name:'Shakshuka', cuisine:'Middle Eastern',
    mode:'beast', time:20, cost:6, fuel:91,
    cal:320, pro:'22g', carb:'28g', fat:'14g', sugar:'8g',
    tags:['protein','veggie'],
    funFact:'"Shakshuka" means "all mixed up" in Arabic slang. One pan, zero dishes, maximum protein — it\'s the ultimate lazy genius meal that looks like you tried really hard 🍳',
    steps:['Heat olive oil, sauté diced onion + garlic until soft 5 mins','Add cumin + smoked paprika, stir 1 minute','Pour in crushed tomatoes, simmer 10 mins until thick','Make 4 wells with a spoon, crack 1 egg into each','Cover and cook 5-7 mins — yolks should still be runny','Serve immediately with crusty bread + crumbled feta'],
    miss:['feta ($3)','crusty bread ($2.50)'],
    tips:['Don\'t overcook the eggs — runny yolk is the goal','Smoked paprika > regular paprika here, trust','Add a pinch of chilli flakes if you want heat'],
  },
  {
    id:4, flag:'🍝', name:'Pasta Aglio e Olio', cuisine:'Italian',
    mode:'snack', time:12, cost:4, fuel:74,
    cal:490, pro:'12g', carb:'70g', fat:'18g', sugar:'2g',
    tags:['carb','quick'],
    funFact:'This is Naples\' famous "midnight pasta" — invented by chefs who\'d finish a late service and make something fast with pantry staples. If it\'s good enough for Italian chefs at 2am, it\'s good enough for your 11pm study session 🌙',
    steps:['Boil spaghetti in heavily salted water until al dente','Heat ¼ cup olive oil on LOW, fry 4 sliced garlic cloves slowly 3 mins','Add chilli flakes, let bloom 30 seconds','Drain pasta, save 1 cup pasta water','Add pasta + splash of pasta water to oil, toss aggressively 2 mins','Finish off heat with parsley + parmesan + extra drizzle'],
    miss:['parmesan ($2)'],
    tips:['LOW heat for garlic — burnt garlic = bitter disaster','Pasta water is liquid gold. Don\'t skip it','The tossing emulsifies the sauce — put your back into it'],
  },
  {
    id:5, flag:'🌯', name:'Chicken Burrito Bowl', cuisine:'Mexican',
    mode:'beast', time:20, cost:6, fuel:85,
    cal:480, pro:'32g', carb:'55g', fat:'11g', sugar:'4g',
    tags:['protein','meal-prep'],
    funFact:'"Burrito" literally means "little donkey" in Spanish. Food historians think it\'s because the wrapped tortilla resembles a bedroll on a donkey\'s back. The most charming origin story in food 🫏',
    steps:['Season chicken thighs with cumin + paprika + garlic powder + salt','Pan fry on medium-high 6 mins each side until golden','Rest 5 mins, then slice or shred','Cook rice, fluff with fork, stir in lime juice + coriander','Heat black beans with cumin + salt in small pot','Bowl: rice base + chicken + beans + salsa + sour cream + lime'],
    miss:['black beans ($1.50)'],
    tips:['Thighs not breasts — juicier and cheaper','Make double rice, it keeps 4 days in the fridge','The lime juice in the rice is non-negotiable'],
  },
  {
    id:6, flag:'🍛', name:'Butter Chicken', cuisine:'Indian',
    mode:'glow', time:30, cost:8, fuel:87,
    cal:520, pro:'32g', carb:'48g', fat:'16g', sugar:'6g',
    tags:['protein','rich'],
    funFact:'Butter chicken (murgh makhani) was invented by accident in 1950s Delhi. A chef at Moti Mahal restaurant mixed leftover chicken into a tomato-butter gravy he\'d made. Best culinary accident in history 🧈',
    steps:['Dice chicken, marinate in yogurt + turmeric + cumin 10 mins','Fry chicken on high heat until lightly charred, set aside','Sauté onion + garlic + ginger until golden in same pan','Add tomato paste + garam masala + chilli + big knob of butter','Pour in cream, stir well, return chicken, simmer 15 mins','Serve over basmati rice with naan for scooping'],
    miss:['garam masala ($2.50)','cream ($2)'],
    tips:['The char on the chicken is essential for flavour','Don\'t rush the onion — it needs to go golden','This is even better the next day after the spices develop'],
  },
  {
    id:7, flag:'🍱', name:'Korean Bibimbap', cuisine:'Korean',
    mode:'beast', time:20, cost:7, fuel:90,
    cal:480, pro:'30g', carb:'60g', fat:'11g', sugar:'5g',
    tags:['protein','balanced'],
    funFact:'"Bibimbap" literally means "mixed rice" in Korean. Buddhist monks created it as a way to use up all vegetables before meditation. It\'s basically a 1,000-year-old meal prep strategy 🧘',
    steps:['Cook short-grain rice until fluffy, season with sesame oil','Sauté baby spinach with garlic + sesame oil until wilted','Blanch bean sprouts 2 mins, cool, toss with salt + sesame oil','Julienne carrot, stir-fry in sesame oil 2 mins','Fry egg sunny-side up — yolk must stay runny','Bowl: rice base, arrange veg in coloured sections, place egg, add gochujang'],
    miss:['gochujang ($3.50)','spinach ($2)'],
    tips:['Use a stone bowl (dolsot) if you have one — crispy rice bottom is the goal','Mix everything vigorously before eating','Sesame oil is the secret ingredient — don\'t skip it'],
  },
  {
    id:8, flag:'🫓', name:'Halloumi Wrap', cuisine:'Mediterranean',
    mode:'snack', time:10, cost:6, fuel:77,
    cal:390, pro:'20g', carb:'45g', fat:'16g', sugar:'3g',
    tags:['quick','veggie'],
    funFact:'Halloumi comes from Cyprus and has an unusually high melting point due to its low acid content. Scientists call it "a cheese with structural integrity." It literally stands firm under pressure. A role model 🧀',
    steps:['Slice halloumi into 1cm thick planks — no oil needed','Pan fry on HIGH heat 2 minutes per side until deep golden crust','Warm flatbread in the same pan for 30 seconds each side','Spread hummus generously across the entire bread','Layer halloumi + roasted capsicum + fresh rocket + chilli sauce','Roll tight from the bottom, slice diagonally, eat immediately'],
    miss:['halloumi ($4)','hummus ($2)'],
    tips:['HIGH heat is non-negotiable — low heat = rubbery disaster','Eat immediately, halloumi gets chewy when it cools','Chilli sauce + hummus combo is a flavour unlock'],
  },
  {
    id:9, flag:'🌮', name:'Tacos Al Pastor', cuisine:'Mexican',
    mode:'glow', time:20, cost:6, fuel:83,
    cal:460, pro:'26g', carb:'55g', fat:'12g', sugar:'6g',
    tags:['protein','fun'],
    funFact:'Al Pastor was introduced to Mexico by Lebanese immigrants in the 1930s — it\'s literally a Mexican interpretation of shawarma. A perfect example of food diplomacy. The world is better for it 🌍',
    steps:['Slice pork thin, marinate in chipotle + pineapple juice + cumin 10 mins','Fry on HIGH heat until caramelised and charred at the edges','Warm small corn tortillas in a dry pan 30 seconds each side','Dice fresh pineapple + white onion + coriander for salsa','Mix salsa with squeeze of lime + pinch of salt','Two tortillas stacked + pork + pineapple salsa + hot sauce'],
    miss:['corn tortillas ($3)','chipotle paste ($2.50)'],
    tips:['Double tortillas so they don\'t break — Mexican street taco style','The pineapple in the marinade tenderises the pork','Char on the meat is the whole point — don\'t be scared of high heat'],
  },
  {
    id:10, flag:'🍥', name:'Miso Ramen', cuisine:'Japanese',
    mode:'snack', time:15, cost:6, fuel:79,
    cal:420, pro:'18g', carb:'58g', fat:'10g', sugar:'4g',
    tags:['umami','quick'],
    funFact:'Miso has been fermented in Japan for over 1,300 years. The paste you\'re eating today is made using the same process as monks in the 7th century. Your bowl of ramen is connected to ancient Japan 🏯',
    steps:['Boil ramen noodles per packet (3 min), drain and set aside in bowl','Combine 2 tbsp miso paste + 1 tbsp soy sauce + 1 tsp sesame oil in the bowl','Pour 300ml hot water (not boiling) over the miso, stir until dissolved','Add noodles into the broth and toss to combine','Top with soft-boiled egg + corn kernels + torn nori sheet + spring onion','Finish with a generous drizzle of chilli oil'],
    miss:['miso paste ($3)','nori ($2)'],
    tips:['Never boil the miso — heat destroys the probiotics','Soft-boiled egg: 6 mins 30 seconds in boiling water, ice bath immediately','This is actually surprisingly filling despite being so simple'],
  },
  {
    id:11, flag:'🥙', name:'Greek Salad + Pita', cuisine:'Greek',
    mode:'green', time:10, cost:5, fuel:76,
    cal:310, pro:'14g', carb:'38g', fat:'14g', sugar:'7g',
    tags:['veggie','quick'],
    funFact:'Traditional Greek salad (horiatiki) contains absolutely no lettuce — Greeks consider it unnecessary water. This is a strongly-held national opinion and they will debate you on it. They\'re probably right 🥗',
    steps:['Chop cucumber + tomato + red onion into chunky bite-size pieces','Add kalamata olives + a generous crumble of feta on top (don\'t mix yet)','Dress: 3 tbsp olive oil + 1 tbsp red wine vinegar + dried oregano + salt','Toss gently — you want the veg to stay crisp and the feta in chunks','Warm pita directly over gas flame or in a dry pan 30 sec each side','Serve salad alongside warm pita and scoop it up'],
    miss:['feta ($3)','kalamata olives ($2.50)','pita ($2)'],
    tips:['The feta goes ON TOP, not mixed in — Greek salad law','Let it sit 5 mins after dressing so the tomatoes release juice','Use the best olive oil you have here — it matters'],
  },
  {
    id:12, flag:'🥘', name:'Tom Yum Soup', cuisine:'Thai',
    mode:'green', time:20, cost:7, fuel:89,
    cal:280, pro:'24g', carb:'18g', fat:'8g', sugar:'5g',
    tags:['protein','hearty'],
    funFact:'Tom Yum has been studied by scientists for its anti-inflammatory and anti-bacterial properties. Galangal and lemongrass are genuinely medicinal. Your soup is basically medicine that tastes incredible 🌿',
    steps:['Bruise lemongrass with the back of a knife, slice galangal, boil in 600ml water','Add kaffir lime leaves + mushrooms, simmer 5 minutes','Add prawns or sliced chicken, cook through 4 minutes','Season assertively: fish sauce + fresh lime juice + chilli paste','Stir in a small splash of coconut milk at the end for creaminess','Serve garnished with fresh coriander + sliced red chilli'],
    miss:['lemongrass ($1.50)','kaffir lime leaves ($2)','prawns ($5)'],
    tips:['Taste as you go — it should be sour, spicy, salty, aromatic','The lemongrass and galangal are for flavour only — don\'t eat them','Add the coconut milk last so it doesn\'t split'],
  },
]

// ─── SHOPPING ITEMS ────────────────────────────────────────────
export const SHOP_ITEMS = [
  { id:1,  n:'Garlic (1 bulb)',         p:1.00, e:'🧄', tag:'produce',  done:false },
  { id:2,  n:'Rice noodles (500g)',      p:2.00, e:'🍜', tag:'pantry',   done:false },
  { id:3,  n:'Star anise',              p:1.50, e:'⭐', tag:'spices',   done:false },
  { id:4,  n:'Feta cheese (200g)',       p:3.00, e:'🧀', tag:'dairy',    done:false },
  { id:5,  n:'Parmesan (100g)',          p:2.00, e:'🧀', tag:'dairy',    done:false },
  { id:6,  n:'Lemongrass (4 stalks)',    p:1.50, e:'🌿', tag:'produce',  done:false },
  { id:7,  n:'Gochujang paste',          p:3.50, e:'🌶️',tag:'sauces',   done:false },
  { id:8,  n:'Garam masala',             p:2.50, e:'🫙', tag:'spices',   done:false },
  { id:9,  n:'Fresh cream (300ml)',      p:2.00, e:'🥛', tag:'dairy',    done:false },
  { id:10, n:'Miso paste (200g)',        p:3.00, e:'🍶', tag:'pantry',   done:false },
]

// ─── FOOD PRESERVATION TIPS ────────────────────────────────────
export const FOOD_TIPS = [
  { emoji:'🥬', tip:'Store leafy greens with a paper towel in the bag — absorbs moisture and they last 2x longer' },
  { emoji:'🍅', tip:'Never refrigerate tomatoes — cold kills the flavour. Keep them on the counter' },
  { emoji:'🥑', tip:'Speed-ripen an avocado by putting it in a paper bag with a banana overnight' },
  { emoji:'🧄', tip:'Garlic lasts months at room temp in a dry spot. Fridge makes it sprout faster' },
  { emoji:'🍋', tip:'Freeze lemon juice in ice cube trays — each cube ≈ 1 tbsp, ready whenever you need it' },
  { emoji:'🌿', tip:'Treat fresh herbs like flowers — trim stems, put in a glass of water in the fridge' },
  { emoji:'🍞', tip:'Freeze bread before it goes stale. Toast straight from frozen — tastes fresh' },
  { emoji:'🥚', tip:'Eggs stored with the pointy end down last longer — keeps the yolk centred' },
  { emoji:'🧅', tip:'Keep onions and potatoes separate — onions release gas that makes potatoes sprout' },
  { emoji:'🍄', tip:'Store mushrooms in a paper bag, not plastic — they need to breathe or they get slimy' },
  { emoji:'🥬', tip:'Leafy greens last longer with a paper towel in the bag' },
  { emoji:'🍅', tip:'Never refrigerate tomatoes — keep them on the counter' },
  { emoji:'🥑', tip:'Ripen avocados faster by storing with a banana' },
  { emoji:'🧄', tip:'Store garlic in a dry dark spot, not the fridge' },
  { emoji:'🍋', tip:'Freeze lemon juice in cubes for quick cooking' },
  { emoji:'🌿', tip:'Store herbs like flowers — stems in water' },
  { emoji:'🍞', tip:'Freeze bread early to prevent it going stale' },
  { emoji:'🥚', tip:'Eggs last longer stored pointy side down' },
  { emoji:'🧅', tip:'Keep onions and potatoes separate to prevent sprouting' },
  { emoji:'🍄', tip:'Store mushrooms in paper bags so they can breathe' },
  { emoji:'🍚', tip:'Cooked rice should go in the fridge within 2 hours' },
  { emoji:'🥦', tip:'Wrap broccoli loosely in foil to keep it fresh longer' },
  { emoji:'🥕', tip:'Cut carrot tops before storing to prevent moisture loss' },
  { emoji:'🧀', tip:'Wrap cheese in parchment paper to prevent sweating' },
  { emoji:'🍎', tip:'Apples speed up ripening — keep them away from other fruits' },
  { emoji:'🥬', tip:'Dry lettuce well before storing to avoid soggy leaves' },
  { emoji:'🍗', tip:'Freeze cooked chicken if you won’t eat it in 3 days' },
  { emoji:'🥘', tip:'Most leftovers stay safe in the fridge for 3–4 days' },
  { emoji:'🥔', tip:'Store potatoes in a cool dark place, not the fridge' },
  { emoji:'🧊', tip:'Freeze leftover veggies before they spoil' },
]

// ─── NOTIFICATION MESSAGES ─────────────────────────────────────
export const NOTIF_MSGS = [
   'are u eating instant noodles AGAIN?? mama is NOT okay with this 😤',
  "it's dinner time bestie~ go cook something real pls 🍳",
  "ur lunch slot is empty... the fridge isn't gonna cook itself babes",
  'no cap eating cereal for every meal is NOT it. mama made u a plan 💅',
  'did u actually cook today or are we lying to ourselves rn 👀',
  "gentle reminder~ ur meal plan is all set. don't let mama down! 💕",
  "it's 11pm and no dinner?? mama is genuinely worried fr fr 🌙",
  'bestie ur protein intake today was probably ZERO. beast mode requires effort 💪',
  'mama checked ur plan and ur literally surviving on vibes rn 😭',
  "3 days in a row of takeaway?? ur wallet AND ur body both crying rn 💸",
  'psst… your fridge has ingredients waiting. go cook something 👩‍🍳',
  'exam brain needs fuel — go eat something real 🧠',
  'hydration check bestie 💧 water first, coffee later',
  'mama believes in you… but also believes you should eat vegetables 🥦',
  'gym mode but no protein?? mama confused rn 💪',
  'lazy mode detected… but at least eat something healthy 😌',
  'quick reminder: food = energy = better grades 📚',
  'your future self will thank you for cooking tonight ✨',
  'fridge audit time — eat the leftovers before they revolt 🍱',
  'mama saw your grocery list… proud of you for trying 🥹',
]

// ─── BADGE DEFINITIONS ─────────────────────────────────────────
export const BADGES = [
  { id:'protein-hero',   icon:'🥩', name:'Protein Hero',    desc:'Hit 25g+ protein 3 days',  color:'#FF6B5B' },
  { id:'veggie-queen',   icon:'🥗', name:'Veggie Queen',    desc:'5 veggie meals this week',  color:'#7ED8A4' },
  { id:'meal-planner',   icon:'📅', name:'Meal Planner',    desc:'Plan all 7 days',           color:'#F5C842' },
  { id:'early-bird',     icon:'🌅', name:'Early Bird',      desc:'Breakfast every day',        color:'#B8A0F8' },
  { id:'budget-king',    icon:'💰', name:'Budget King',     desc:'Stay under $8/meal all week',color:'#C8F135' },
  { id:'world-tour',     icon:'🌏', name:'World Tour',      desc:'Try 5 different cuisines',   color:'#60B8FF' },
]
